CREATE DATABASE [BDTEST]
GO

USE [BDTEST]
GO

CREATE TABLE [dbo].[CLIENTES](
	[CODIGO] [varchar](10) NOT NULL,
	[RAZONSOCIAL] [varchar](150) NOT NULL,
	[REGISTRO] [varchar](10) NOT NULL,
	[DIRECCION] [varchar](150) NOT NULL,
	[TIPOCLIENTEID] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TIPOSCLIENTE](
	[TIPOCLIENTEID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TIPOSCLIENTE] PRIMARY KEY CLUSTERED 
(
	[TIPOCLIENTEID] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENTES] ADD  CONSTRAINT [IX_CLIENTES_U_RAZONSOCIAL] UNIQUE NONCLUSTERED 
(
	[RAZONSOCIAL] ASC
)
GO

ALTER TABLE [dbo].[CLIENTES] ADD  CONSTRAINT [IX_CLIENTES_U_REGISTRO] UNIQUE NONCLUSTERED 
(
	[REGISTRO] ASC
)
GO

ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_TIPOSCLIENTE] FOREIGN KEY([TIPOCLIENTEID])
REFERENCES [dbo].[TIPOSCLIENTE] ([TIPOCLIENTEID])
GO

ALTER TABLE [dbo].[CLIENTES] CHECK CONSTRAINT [FK_CLIENTES_TIPOSCLIENTE]
GO

INSERT [dbo].[TIPOSCLIENTE] ([TIPOCLIENTEID], [NOMBRE]) VALUES (1, N'NACIONAL')
GO
INSERT [dbo].[TIPOSCLIENTE] ([TIPOCLIENTEID], [NOMBRE]) VALUES (2, N'EXTRANJERO')
GO
